<?php

declare(strict_types=1);

namespace PrivacyCI\Generation;

use PrivacyCI\Manifest\Classification;
use PrivacyCI\Manifest\LocationKind;

/**
 * Writes the deletion handler a policy implies.
 *
 * The generated file goes into the application's repository and is reviewed as a
 * diff, so we take no runtime risk at all, we emit code, not effects. It is the
 * cheapest real value in the deletion ladder, and generators
 * are native vocabulary in this ecosystem: make:model, make:job, make:policy.
 *
 * Two rules govern the output:
 *
 *   - It must be obviously generated, and obviously in need of review.
 *   - It must never silently omit something. A location the policy did not
 *     classify becomes a loud TODO rather than an absence.
 */
final class HandlerGenerator
{
    /**
     * Rows touched per statement.
     *
     * Large enough that a normal subject finishes in one pass, small enough
     * that an unusual one does not hold a transaction open for minutes.
     */
    private const CHUNK = 1000;

    public function generate(
        HandlerPlan $plan,
        string $namespace = 'App\\Privacy',
        string $class = 'DeleteUser',
        string $subjectType = 'user',
    ): string {
        $body = $this->body($plan);
        $uses = $this->uses($plan);

        $useBlock = $uses === [] ? '' : implode("\n", array_map(
            static fn (string $u): string => "use {$u};",
            $uses,
        ))."\n\n";

        return <<<PHP
        <?php

        declare(strict_types=1);

        namespace {$namespace};

        {$useBlock}/**
         * Generated by `php artisan privacy:make-handler` from your privacy policy.
         *
         * Review it before merging, and own it afterwards, this file is yours.
         * Regenerating overwrites it, so once you have edited it by hand, keep
         * editing by hand.
         *
         * Order matters. Rows furthest from the {$subjectType} go first and the
         * {$subjectType}'s own row goes last, so foreign keys stay satisfied throughout.
         * Non-database stores are cleared before any row is touched, because once
         * the row is gone its key pattern can no longer be resolved.
         */
        final class {$class} implements SubjectDeleter
        {
            public function delete(DeletionRequest \$request): void
            {
                \$subjectId = \$request->subjectId;

        {$body}    }
        }

        PHP;
    }

    private function body(HandlerPlan $plan): string
    {
        $lines = [];

        foreach ($plan->steps as $step) {
            $lines[] = $this->step($step);
        }

        if ($plan->unresolved !== []) {
            $lines[] = $this->unresolved($plan->unresolved);
        }

        if ($lines === []) {
            $lines[] = $this->indent([
                '// Your policy classified nothing as deletable.',
                '// Run `php artisan privacy:discover` to see what was found.',
            ]);
        }

        return implode("\n", $lines);
    }

    private function step(HandlerStep $step): string
    {
        $out = [];

        foreach ($step->notes as $note) {
            $out[] = "// {$note}";
        }

        if (! $step->actionable) {
            // RETAIN is a deliberate decision, so the reason is the whole story.
            // Anything else non-actionable is genuinely unfinished and says so.
            if ($step->classification !== Classification::Retain) {
                $out[] = sprintf('// TODO: %s (%s)', $step->label, $step->classification->value);
            }

            return $this->indent($out);
        }

        $out = array_merge($out, match (true) {
            $step->handler !== null => $this->customLines($step),
            $step->pattern !== null => $this->storeLines($step),
            $step->classification === Classification::Anonymize => $this->anonymizeLines($step),
            $step->classification === Classification::Delete => $this->deleteLines($step),
            default => ['// '.$step->label.' ('.$step->classification->value.')'],
        });

        return $this->indent($out);
    }

    /** @return list<string> */
    private function customLines(HandlerStep $step): array
    {
        return [sprintf('app(\\%s::class)->handle($request);', ltrim((string) $step->handler, '\\'))];
    }

    /** @return list<string> */
    private function storeLines(HandlerStep $step): array
    {
        $pattern = $this->interpolate((string) $step->pattern);
        $store = (string) $step->store;

        return match (true) {
            $step->kindIsStorage() => [
                sprintf("Storage::disk('%s')->delete(\"%s\");", $store, $pattern),
            ],
            // Written through the cache, so clear it through the cache.
            $store === 'cache' => [sprintf('Cache::forget("%s");', $pattern)],
            default => [sprintf('Redis::del("%s");', $pattern)],
        };
    }

    /** @return list<string> */
    private function anonymizeLines(HandlerStep $step): array
    {
        // The subject's own row: exactly one, and the key it is found by is not
        // among the columns being nulled, so a loop would never end.
        if ($step->isSubjectRoot) {
            return [
                $this->queryStart($step),
                sprintf("    ->where('%s', \$subjectId)", (string) $step->foreignKey),
                '    ->update([',
                ...$this->pairs($step, 8),
                '    ]);',
            ];
        }

        $pairs = $this->pairs($step, 12);

        // Chunked for the same reason deletes are: one subject can own millions
        // of rows, and a single UPDATE over all of them is one very long
        // transaction. The loop ends when nothing matches any more, which for
        // anonymisation is also the proof that the link is gone.
        return [
            sprintf('// Terminates because %s is among the columns being nulled,', (string) $step->foreignKey),
            '// so the next pass matches nothing. Keep it that way if you edit this.',
            'do {',
            sprintf('    $affected = %s', $this->queryStart($step)),
            sprintf("        ->where('%s', \$subjectId)", (string) $step->foreignKey),
            sprintf('        ->limit(%d)', self::CHUNK),
            '        ->update([',
            ...$pairs,
            '        ]);',
            '} while ($affected > 0);',
        ];
    }

    /**
     * Replacement lines at a given indent, since the chunked form nests deeper.
     *
     * @return list<string>
     */
    private function pairs(HandlerStep $step, int $indent): array
    {
        $lines = [];

        foreach ($step->replacements as $column => $value) {
            $lines[] = str_repeat(' ', $indent).sprintf("'%s' => %s,", $column, $this->literal($value));
        }

        return $lines;
    }

    /** @return list<string> */
    private function deleteLines(HandlerStep $step): array
    {
        if ($step->isSubjectRoot || $step->foreignKey === null) {
            // The subject's own row: exactly one, so nothing to chunk.
            // whereKey() is Eloquent-only, so a table with no model has to name
            // its key column explicitly.
            return [$step->modelClass !== null
                ? sprintf('%s->whereKey($subjectId)->delete();', $this->queryStart($step))
                : sprintf("%s->where('%s', \$subjectId)->delete();", $this->queryStart($step), $step->foreignKey ?? 'id')];
        }

        // One subject can own millions of dependent rows. Deleting them in a
        // single statement means one enormous transaction: lock contention,
        // replication lag, and a timeout that rolls back twenty minutes of work.
        return [
            'do {',
            sprintf('    $deleted = %s', $this->queryStart($step)),
            sprintf("        ->where('%s', \$subjectId)", $step->foreignKey),
            sprintf('        ->limit(%d)', self::CHUNK),
            '        ->delete();',
            '} while ($deleted > 0);',
        ];
    }

    /**
     * Opens a query for a step.
     *
     * Returns a complete expression rather than a class reference: Eloquent
     * needs ::query() appended and the query builder must not have it, and
     * leaving that to the caller produced `DB::table('x')::query()`.
     */
    private function queryStart(HandlerStep $step): string
    {
        if ($step->modelClass !== null) {
            return '\\'.ltrim($step->modelClass, '\\').'::query()';
        }

        // No model was found for this table, so fall back to the query builder
        // rather than inventing a class name that does not exist.
        return sprintf("DB::table('%s')", (string) $step->table);
    }

    /** @param list<string> $unresolved */
    private function unresolved(array $unresolved): string
    {
        $lines = [
            '// TODO: these locations have no policy and are therefore untouched.',
            '// Classify them in your privacy policy and regenerate.',
        ];

        foreach ($unresolved as $path) {
            $lines[] = "//   - {$path}";
        }

        return $this->indent($lines);
    }

    /** @return list<string> */
    private function uses(HandlerPlan $plan): array
    {
        $uses = [
            'PrivacyCI\\Lifecycle\\DeletionRequest',
            'PrivacyCI\\Lifecycle\\SubjectDeleter',
        ];

        foreach ($plan->steps as $step) {
            if (! $step->actionable) {
                continue;
            }

            if ($step->pattern !== null) {
                $uses[] = match (true) {
                    $step->kindIsStorage() => 'Illuminate\\Support\\Facades\\Storage',
                    $step->store === 'cache' => 'Illuminate\\Support\\Facades\\Cache',
                    default => 'Illuminate\\Support\\Facades\\Redis',
                };
            }

            if ($step->pattern === null && $step->modelClass === null && $step->handler === null) {
                $uses[] = 'Illuminate\\Support\\Facades\\DB';
            }
        }

        $uses = array_values(array_unique($uses));
        sort($uses);

        return $uses;
    }

    /** Rewrites policy placeholders into the generated variable. */
    private function interpolate(string $pattern): string
    {
        return str_replace(
            ['{id}', '{user.id}', '{userId}', '{?}'],
            '{$subjectId}',
            $pattern,
        );
    }

    private function literal(mixed $value): string
    {
        return match (true) {
            $value === null => 'null',
            is_bool($value) => $value ? 'true' : 'false',
            is_int($value), is_float($value) => (string) $value,
            default => "'".str_replace("'", "\\'", (string) $value)."'",
        };
    }

    /** @param list<string> $lines */
    private function indent(array $lines): string
    {
        return implode("\n", array_map(
            static fn (string $l): string => $l === '' ? '' : '        '.$l,
            $lines,
        ))."\n";
    }
}
