<?php

declare(strict_types=1);

namespace PrivacyCI\Generation;

use PrivacyCI\Discovery\Models\ModelMap;
use PrivacyCI\Manifest\Linkage;
use PrivacyCI\Manifest\Location;
use PrivacyCI\Manifest\LocationKind;
use PrivacyCI\Manifest\Manifest;
use PrivacyCI\Manifest\Subject;

/**
 * Scaffolds a privacy policy from what discovery found.
 *
 * Every rule is emitted **commented out**. That is the product's founding
 * principle, not timidity: auto-discovery suggests, developers decide, and
 * nothing destructive happens because a scanner found a field.
 * An uncommented `delete()` here would become real deletion code the moment
 * someone ran `privacy:make-handler`.
 *
 * So the job is to make each decision fast rather than to make it for them:
 * findings grouped by table, evidence inline and the most plausible rule
 * already written on the line below.
 */
final class PolicyGenerator
{
    public function generate(
        Manifest $manifest,
        Subject $subject,
        ModelMap $models = new ModelMap,
        string $namespace = 'App\\Privacy',
        string $class = 'UserPrivacyPolicy',
        bool $onlyBlocking = false,
    ): string {
        $rootModel = $models->forTable($subject->rootTable());
        $modelImport = $rootModel !== null ? "use {$rootModel->class};\n" : '';
        $subjectRef = $rootModel !== null ? $rootModel->shortName().'::class' : "'".$subject->rootTable()."'";

        $body = $this->body($manifest, $subject, $models, $onlyBlocking);

        return <<<PHP
        <?php

        declare(strict_types=1);

        namespace {$namespace};

        {$modelImport}use PrivacyCI\\Policy\\PrivacyPolicy;

        /**
         * Generated by `php artisan privacy:make-policy`.
         *
         * Every rule below is commented out on purpose. Discovery suggests; you
         * decide. Uncommenting a line is a decision to act on that data,
         * `privacy:make-handler` turns these into real deletion code, so read
         * each one before enabling it.
         *
         *   delete()     remove it entirely
         *   anonymize()  keep the row, drop the link and the identifiers
         *   retain()     keep it, with a documented reason (required)
         *   ignore()     not personal data, with a documented reason (required)
         *   custom()     your own handler class
         *
         * Anything left unclassified keeps failing `privacy:check`, which is the
         * point: an undecided location is not the same as a harmless one.
         */
        final class {$class} extends PrivacyPolicy
        {
            public function configure(): void
            {
                \$this->subject({$subjectRef});

        {$body}    }
        }

        PHP;
    }

    private function body(
        Manifest $manifest,
        Subject $subject,
        ModelMap $models,
        bool $onlyBlocking,
    ): string {
        /** @var array<string, list<Location>> $tables */
        $tables = [];
        $stores = [];

        foreach ($manifest->locations() as $location) {
            if ($location->classification->isResolved()) {
                continue;
            }

            if ($onlyBlocking && ! $location->blocksBuild()) {
                continue;
            }

            if ($location->kind === LocationKind::DatabaseColumn) {
                $tables[$this->table($location->path)][] = $location;
            } else {
                $stores[] = $location;
            }
        }

        if ($tables === [] && $stores === []) {
            return $this->indent(['// Nothing left to classify.']);
        }

        $blocks = [];

        // Certain findings first: they are what fails the build today.
        uasort($tables, fn (array $a, array $b): int => [$this->rank($b), $this->table($b[0]->path)]
            <=> [$this->rank($a), $this->table($a[0]->path)]);

        foreach ($tables as $table => $locations) {
            $blocks[] = $this->tableBlock($table, $locations, $subject, $models);
        }

        foreach ($stores as $location) {
            $blocks[] = $this->storeBlock($location);
        }

        return implode("\n", $blocks);
    }

    /** @param list<Location> $locations */
    private function tableBlock(
        string $table,
        array $locations,
        Subject $subject,
        ModelMap $models,
    ): string {
        $isRoot = $table === $subject->rootTable();
        $foreignKey = $this->foreignKey($locations);
        $model = $models->forTable($table);
        $target = $model !== null ? $model->shortName().'::class' : "'{$table}'";

        $lines = [
            sprintf('// %s %s', $this->rule("── {$table} ", 46), $this->headline($isRoot, $foreignKey)),
        ];

        foreach ($locations as $location) {
            $lines[] = sprintf(
                '//    %s  %.2f  %s',
                str_pad($this->column($location->path), 28),
                $location->confidence,
                $this->why($location),
            );
        }

        $lines[] = '';

        foreach ($this->suggestions($isRoot, $foreignKey, $target, $locations) as $suggestion) {
            $lines[] = $suggestion;
        }

        return $this->indent($lines);
    }

    /**
     * @param  list<Location>  $locations
     * @return list<string>
     */
    private function suggestions(
        bool $isRoot,
        ?string $foreignKey,
        string $target,
        array $locations,
    ): array {
        if ($isRoot) {
            // Both, because the choice is real and neither is obviously right.
            // Deleting the row forces every foreign key pointing at it to be
            // nullable or cascading; masking keeps orders, comments and audit
            // rows attributable to somebody, just not to a person.
            return [
                '// $this->delete('.$target.');',
                '// $this->anonymize('.$target.', ['.$this->maskSuggestion($locations).']);',
                '//   Masking keeps the row so foreign keys survive. Use placeholders,',
                '//   not null: identifying columns are usually NOT NULL.',
            ];
        }

        if ($foreignKey === null) {
            // Nothing here addresses the subject, so no generated rule could work.
            return [
                '// No foreign key to the subject, so a generated handler cannot look these',
                '// rows up. Supply the lookup yourself, or rule the table out:',
                '// $this->custom('.$target.', \\App\\Privacy\\PurgeTheseRows::class);',
                '// $this->ignore('.$target.')->reason("");',
            ];
        }

        $columns = [$foreignKey];

        foreach ($locations as $location) {
            $column = $this->column($location->path);

            if ($column !== $foreignKey && $location->linkage === Linkage::Heuristic) {
                $columns[] = $column;
            }
        }

        $columns = array_values(array_unique($columns));
        sort($columns);

        $pairs = implode(', ', array_map(
            static fn (string $c): string => "'{$c}' => null",
            $columns,
        ));

        return [
            '// $this->anonymize('.$target.', ['.$pairs.']);',
            '// $this->delete('.$target.');',
        ];
    }

    /**
     * A starting set of placeholders for masking the subject.
     *
     * Uses the columns actually discovered on the root, with values that are
     * obviously not real, so an unedited placeholder is visible in the data
     * rather than looking like somebody's name.
     *
     * @param  list<Location>  $locations
     */
    private function maskSuggestion(array $locations): string
    {
        $pairs = [];

        foreach ($locations as $location) {
            $column = $this->column($location->path);

            if ($location->linkage === Linkage::SubjectRoot) {
                continue;   // the key identifies the row and has to survive
            }

            $pairs[$column] = match (true) {
                str_contains($column, 'email') => "'deleted@example.invalid'",
                str_contains($column, 'name') => "'Deleted user'",
                str_contains($column, 'phone') => "''",
                default => "''",
            };
        }

        if ($pairs === []) {
            return '';
        }

        ksort($pairs);
        $pairs = array_slice($pairs, 0, 6, true);

        return implode(', ', array_map(
            static fn (string $c, string $v): string => "'{$c}' => {$v}",
            array_keys($pairs),
            $pairs,
        ));
    }

    private function storeBlock(Location $location): string
    {
        $method = match ($location->kind) {
            LocationKind::ObjectStorage => 'deleteStorage',
            LocationKind::SearchIndex => 'deleteSearch',
            LocationKind::ExternalService => 'deleteService',
            default => 'deleteRedis',
        };

        $note = $location->linkage === Linkage::Inferred
            ? 'inferred by static analysis, confirm the key before enabling'
            : 'declared';

        $call = $method === 'deleteStorage'
            ? sprintf("// \$this->%s('%s', disk: '%s');", $method, $location->path, $location->store)
            : sprintf("// \$this->%s('%s');", $method, $location->path);

        return $this->indent([
            sprintf('// %s %s', $this->rule("── {$location->store}: {$location->path} ", 46), $note),
            '',
            $call,
        ]);
    }

    /**
     * Pads with a box-drawing rule by character count, not byte count.
     *
     * str_pad() measures bytes, and '─' is three of them, so padding to a fixed
     * width slices the final character in half and corrupts the file.
     */
    private function rule(string $label, int $width): string
    {
        $fill = max(0, $width - mb_strlen($label));

        return $label.str_repeat('─', $fill);
    }

    /** Prefer the evidence that names *what* the data is over where it sits. */
    private function why(Location $location): string
    {
        foreach ($location->evidence as $line) {
            if (str_starts_with($line, 'column name matches ')) {
                return substr($line, strlen('column name matches '));
            }
        }

        return $location->evidence[0] ?? $location->linkage->value;
    }

    private function headline(bool $isRoot, ?string $foreignKey): string
    {
        return match (true) {
            $isRoot => 'subject root',
            $foreignKey !== null => 'linked by '.$foreignKey,
            default => 'no link to the subject',
        };
    }

    /** @param list<Location> $locations */
    private function rank(array $locations): int
    {
        foreach ($locations as $location) {
            if ($location->blocksBuild()) {
                return 2;
            }
        }

        return 1;
    }

    /** @param list<Location> $locations */
    private function foreignKey(array $locations): ?string
    {
        foreach ($locations as $location) {
            if (in_array($location->linkage, [Linkage::ForeignKey, Linkage::Relationship], true)) {
                return $this->column($location->path);
            }

            if ($location->linkage === Linkage::SubjectRoot) {
                return null;
            }
        }

        return null;
    }

    private function table(string $path): string
    {
        $pos = strrpos($path, '.');

        return $pos === false ? $path : substr($path, 0, $pos);
    }

    private function column(string $path): string
    {
        $pos = strrpos($path, '.');

        return $pos === false ? $path : substr($path, $pos + 1);
    }

    /** @param list<string> $lines */
    private function indent(array $lines): string
    {
        return implode("\n", array_map(
            static fn (string $l): string => $l === '' ? '' : '        '.$l,
            $lines,
        ))."\n";
    }
}
